version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_sb_challenge
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    environment:
      - APP_PORT=3000
      - SECRET_JWT_USER=LifeBeforeDeath
      - DB_NAME=db_sb_challenge
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=mysqldb
      - DB_DIALECT=mysql
      - DB_PORT=3306
volumes:
  db:
